### ISSUE TITLE
Consider citing original research

### ISSUE THREAD

**Issue by Brandon7CC** [outflanknl/edr-internals#1]
Hi Kyle,

I recently came across [your blog here](https://www.outflank.nl/blog/2024/06/03/edr-internals-macos-linux/) where you go through using Mac Monitor to show how we can intercept an arbitrary ES client making its event subscriptions. 

Your blog does an excellent job showcasing how we can pull back the details on clients in this way :)

If possible, I'd also like to request that my original research here is cited for the `libEndpointSecurity.dylib` / Frida components:
* Original RE work: https://github.com/redcanaryco/mac-monitor/wiki/8.-Endpoint-Security-DYLIB#an-arbitrary-clients-event-subscriptions
* Original Frida script: https://gist.github.com/Brandon7CC/e5e54978b1484fd09f5e201a4fd9dbfc

Thank you and great job again!

**Comment by kyleavery** [comment]
Wow, you're absolutely right! I'll update our repo/blog shortly. The Mac Monitor wiki had some useful information and I completely forgot about your Frida script - my apologies!

**Comment by kyleavery** [comment]
https://github.com/outflanknl/edr-internals/commit/ca3afc9afcc6209b3a71bc96c3bb7cb954e98ba3
